---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: testinfra
  enabled: true
  options:
    verbose: true
    capture: no
  additional_files_or_dirs:
    - test_*.py
    - tests/