---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  options:
    roles_path: ${MOLECULE_SCENARIO_DIRECTORY}/../..

verifier:
  name: testinfra
