---
all:
  children:
    molecule:
      hosts:
        molecule-fedora:
          ansible_connection: containers.podman.podman
          container_image: ghcr.io/ansible/community-ansible-dev-tools:latest
          # container_image: docker.io/fedora:44
          container_command: sleep 1d
          container_privileged: false
