---
- name: Create container instances
  hosts: localhost
  # gather_facts: true
  # become: false
  # become_method: "ansible.builtin.sudo"
  # become_ask_pass: false # https://docs.ansible.com/projects/ansible/latest/reference_appendices/config.html#default-become-ask-pass
  # become_user: root
  # become: true
  # become_user: root
  tasks:
    - name: Create containers from inventory
      containers.podman.podman_container:
        hostname: "{{ item }}"
        name: "{{ item }}"
        image: "{{ hostvars[item]['container_image'] }}"
        command: "{{ hostvars[item]['container_command'] | default('sleep 1d') }}"
        privileged: "{{ hostvars[item]['container_privileged'] | default(false) }}"
        volumes: "{{ hostvars[item]['container_volumes'] | default(omit) }}"
        capabilities: "{{ hostvars[item]['container_capabilities'] | default(omit) }}"
        systemd: "{{ hostvars[item]['container_systemd'] | default(false) }}"
        log_driver: "{{ hostvars[item]['container_log_driver'] | default('json-file') }}"
        state: started
      register: result
      loop: "{{ groups['molecule'] }}"

    - name: Verify containers are running in error state
      ansible.builtin.include_tasks:
        file: tasks/create-fail.yml
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Wait for containers to be ready
      ansible.builtin.wait_for_connection:
        timeout: 30
      delegate_to: "{{ item }}"
      loop: "{{ groups['molecule'] }}"

    - name: Afficher ansible_os_family
      ansible.builtin.debug:
        msg: "La famille OS est : {{ ansible_os_family }}, et le become_user est {{ become_user | default('rien_ni_personne') }}"
    - name: Afficher ansible_distribution
      ansible.builtin.debug:
        msg: "La distribution est : {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"

    - name: "== Create == Install a list of packages"
      ansible.builtin.dnf:
        name:
          - systemd
          - openssh-server
        state: present
      delegate_to: "{{ item }}"
      loop: "{{ groups['molecule'] }}"
      # when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'
