---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

ansible:
  cfg:
    defaults:
      collections_path: collections
      inventory: inventory.yml

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
