---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: podman

# platforms:
#   - name: instance
#     # privileged: true
#     # override_command: false
#     # user: root
#     image: docker.io/fedora:latest
#     # image: docker.io/rockylinux/rockylinux:9
#     # image: docker.io/debian:13
#     # image: docker.io/debian:13-slim
#     # image: quay.io/lib/debian:13-slim
#     pre_build_image: true

provisioner:
  name: ansible
#  options:
#    become: false
  playbooks:
    converge: converge.yml

ansible:
  cfg:
    defaults:
      deprecation_warnings: false
  executor:
    args:
      ansible_playbook:
        - --inventory=inventory/

scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
